//
// Created by Andreea on 11/26/2019.
//

#ifndef FOOD_ORDERING_CONSTANTS_H
#define FOOD_ORDERING_CONSTANTS_H

#define MAX_FOOD_NAME 10
#define MAX_FOOD_TYPES_NO 4
#define MAX_FOOD_TYPES_NAME 20
#define MAX_DRINKS_NAME 12
#define MAX_ADDITIONAL_INFO 200
#define MAX_USERNAME 20
#define MAX_PASSWORD 20
#define INPUT_PERSONAL_DATA_STEP 0
#define CHOOSE_FOOD_STEP 1
#define CHOOSE_FOOD_TYPE_STEP 2
#define CHOOSE_DRINKS_STEP 3
#define CHOOSE_CUTLERY_STEP 4
#define ADDITIONAL_INFO_STEP 5
#define PRINT_ORDER_STEP 6
#define LOAD_DATA "Please load the data"
#define MAX_LINE 256

#endif //FOOD_ORDERING_CONSTANTS_H
